### ISSUE TITLE
Question...

### ISSUE THREAD

**Issue by seanbecker15** [Meegul/better-particles#1]
Just curious if you remember how you tested performance?

**Comment by Meegul** [comment]
The testing was done client-side on a real device. There is a frame-time overlay mode available by using `frameTime: true` in the config object passed to the `Particles` constructor. You can see this in action [here](http://www.michaelbilstein.com/better-particles/) by clicking the "Toggle Frame-time Counter" in the top bar. 

The stated benchmark of 1000 particles with real-time n-body gravity used this frame-time counter and was able to maintain 60fps (a combined physics + render latency of < 16.67ms) on a base-model 2015 13" MBP, though with more recent hardware, it should be fairly easy to exceed that particle count while maintaining 60fps.

**Comment by Meegul** [comment]
The physics latency could stand to be substantially improved by implementing a tree-based approach like the [Barnes-Hut algorithm](https://en.wikipedia.org/wiki/Barnes%E2%80%93Hut_simulation), which should reduce the amortized complexity of the physics down from O(N^2) to O(NLogN). In some preliminary testing I've done, there is some overhead associated with using this data structure that reduced performance for small particle counts, but greatly improved performance in particle counts greater than about a hundred.

**Comment by seanbecker15** [comment]
Beautiful, thanks! I might yonk that frame counter concept for some smart tv stuff I'm working on. You might find it interesting - I'll send the link once I'm done.
